### PR TITLE
[kf5-calendarcore] Changed the formation of periodic events. JB#43300

### PR DESCRIPTION
**Pull request by dkotin11**

### CODE REVIEW

**Comment by pvuorela** [comment]
I'd be very careful on this sort of changes. Actually wouldn't necessarily want to accept such as a patch, but rather via upstream. If you can assure them this is a good idea I'm ok for updating to latest version.

**Comment by pvuorela** [comment]
Commented on the bug. The recurrence style should be explicit. I'd expect this change to cause other problems.

**Comment by dkotin11** [comment]
I checked, drove.
We couldn't find any side effects

**Comment by pvuorela** [comment]
By other problems I mean that the recurrence rule behavior is defined in iCalendar RFC. I think the fix here is at the same time violation of those rules.

**Comment by pvuorela** [comment]
Closing this. Let's make the rule explicit in the UI and middleware when it's wanted that something is the last day of the month or similar.

**Comment by dkotin11** [comment]
Now we are talking about events on the last day of the month.
dates of such events are calculated on kcalendarcore module  recurccerule - file.

we take the month of interest with the first day, and put the date of the event in it.  Due to this algorithm, non-existent dates came to the function getDates().
 
elsewhere, the dates of the monthly event are not calculated.  

The rule is set deeper. But the rule is correct. And the calculation of dates takes place right here

**Comment by pvuorela** [comment]
If you think calendarcore is handling something wrong, would you have a corresponding recurrence rule string? If there's such a rule, it should be fixed upstream.

**Comment by dkotin11** [comment]
The problem is not the rule.
The problem is how dates are calculated according to this rule
calculation algorithm in calendarcore

**Comment by pvuorela** [comment]
If there's a problem how dates are calculated, surely there's a rule that triggers such a problem.

**Comment by dkotin11** [comment]
sorry, let's clarify the terminology.
rule - it is dates rule.  for example - everyday, everymonth, etc.

here the rule is every month.  this rule only has a start date.  all following dates of this rule are calculated.

the problem is in calculating these dates.

If the start date is October 31st.
under this rule we take the first day of the month.  increase the month by one, set the date that was in the start date
Result November 31st,  
this is a non-valid date

**Comment by pvuorela** [comment]
Getting more to code level, I could agree with that if RecurrenceRule::getNextDate(QDate(2021, 11, 1)) returns 31.11.2021. That would be wrong since no such days exists. It should return 31.12.2021.

And you say above problem currently triggers and with these changes gets that latter instead?

**Comment by dkotin11** [comment]
Not certainly in that way
RecurrenceRule::getNextDate(QDate(2021, 11, 1)) returns 31.11.2021  (Novemder)
this date will be ignored.  

date 31.12.2021 (December)   will return on next iteration
we lost date 31.11.2021 (November).   Should have received  30.11.2021 

now monthly events on the 31st,   there is not for every month, but only where there is 31

I made corrections so that the events would be monthly. And if it is the 31st, what would the event be postponed to 30 (the last day of the month)  (for February 28 or 29)

**Comment by dkotin11** [comment]
if you think this behavior needs a new rule, then I will raise this issue

**Comment by pvuorela** [comment]
Now we are getting again to the actual specification etc. If the recurrence rule is for 31st  day, the output should be only 31st day. Not 30, not 29, not 28. For the last day or second last day recall the specification has negative days. Possibly also on the RecurrenceRule.

**Comment by dkotin11** [comment]
thanks, now I understand.
With negative days, I will be able to make fix in UI only

**Comment by pvuorela** [comment]
Yes exactly, the user should choose if 31st repeating means repeating on exact date or repeating in last day of the month.

**Comment by dkotin11** [comment]
I checked everything again. There is a problem.
 A decision through negative dates is not possible. It will not repeat the behavior of Exchange.
 
At first glance, you can really get by with negative dates. For example 31 numbers are always considered -1 numbers. Then, in months with 30 days and February, the event will come on the 30th (or 28th for February) day.
But the problem lies with the 30th and 29th numbers. The event on the 30th is not the events of the last day of the month (it must not occur on the 31st for months where there are 31 days. However, it must occur on the 28th for February. Due to the presence of February, the last days of the month cannot be dispensed with.

Exchange algorithm.
We determine the date by superimposing the existing day on the new month. For example, we get November 31st. if this is not an existing date, and it is more than the number of days in this month, then we take the largest date possible for this month (from November 31 we make November 30). This is how Exchange works 
We cannot afford behavior that is different from that of Exchange

**Comment by pvuorela** [comment]
> The event on the 30th is not the events of the last day of the month (it must not occur on the 31st for months where there are 31 days. However, it must occur on the 28th for February. Due to the presence of February, the last days of the month cannot be dispensed with.

Sounds like a problematic case, but then again not sure how to even present that to the user in the recurrence UI.

> We determine the date by superimposing the existing day on the new month. For example, we get November 31st. if this is not an existing date, and it is more than the number of days in this month, then we take the largest date possible for this month (from November 31 we make November 30). This is how Exchange works
We cannot afford behavior that is different from that of Exchange

Do you have a link to Exchange protocol specification that specifies the recurrence handling? 

Anyhow, if exchange sync is implemented on top of iCalendar spec/API, the exchange sync needs to adapt to what they provide. Not the other way around.

**Comment by dkotin11** [comment]
if we consider the 31st day as the last day of the month, then this works only for 31 numbers 
they become 30 or 28 in February. 

But that doesn't work for 30 numbers.
There is no 30th in the Febгuary. Therefore, we must calculate the 28th as the last day of the month.
but for January, 30th is not the last day 

we cannot repeat the behavior of the Exchanges with the help of recent days (or different combinations of negative and positive days)

**Comment by pvuorela** [comment]
So what I earlier tested Exchange it didn't work as expected here.

But granted that the exchange protocol might support different types of recurrence. Even on that case you should very carefully read the protocol specification on how recurrence is expected to happen. If you find something, please link the protocol description page.

Then again, even if you want to have option "30th or the last day of the month if month is shorter", I'm wondering how would you present the recurrence option to the user in the application. It can't be "recurring every month" because that's 30th. It can't be "last day of the month" because that's then also 31st day. And that "...or the last..." gets somewhat complicated as a string.

And then again, even if you come up with some extra recurrence rule option that would be understandable by the user, is there really enough real life need? My Teams app nor outlook web neither have an option for that. I have options for "last <weekday> of month" or "recurring monthly" which means exactly 30th or 31st. Not even last day of the month is presented as an option.

**Comment by dkotin11** [comment]
rechecked everything again.

the rule that a monthly event is repeated every month is strictly enforced.

1. If I select an event on the 30th. And repeat it monthly. It will be February 28th.
2. If I choose to repeat the event every 1 month, on the same day, 30th. This is a strict instruction to do on a specific day. It will still be February 28th.
The installation does not work on the exact day (if it contradicts the rule, the monthly event must be at least once a month)

Now I'm looking for it in the protocol description.


For the user, we want to present it with no choice. Since it is now implemented, for example, in Web Outlook

**Comment by dkotin11** [comment]
to determine the monthly day of caldav-services and exchange behave differently.

caldav-services accurately determine the 31st day (and do not make an event in months where there are 30 days). exchange always makes an event without missing months.

**Comment by dkotin11** [comment]
need to create a new monthly rule, exclusively for exchange.  
these are big changes. More than this PR

**Comment by dcaliste** [comment]
In RFC5545 (CalDAV protocol), you can define a RRULE that will occur the 30th of every month or last day of the month if the 30th doesn't exist :
`RRULE:FREQ=MONTHLY;BYSETPOS=-1;BYMONTHDAY=28,29,30`

Play with https://jakubroztocil.github.io/rrule/ for a lot of fun with the RRULEs… : /

All that being said, I've no idea if KCalendarCore is generating a proper set of occurrences for this rule.

**Pull request closed without merging**
