### PR TITLE
[kf5-calendarcore] Update from upstream, adding support for pkgconfig…

### PR DESCRIPTION
**Pull request by dcaliste**
… file.

@pvuorela and @chriadam, it appeared that Neochapay contributed upstream the support to add a pkg-config file. This MR is pulling the latest upstream and removing our patch adding support for such file. The upstream contains also one or two bug fixes.

### CODE REVIEW

**Comment by chriadam** [comment]
@pvuorela @llewelld  seems fine to me... do you agree?

**Comment by chriadam** [comment]
@pvuorela also which bug number should be used for such "update to latest upstream" changes?

**Comment by pvuorela** [comment]
Yep, seems quite fine. Let's merge, I'll come up with some bug with an annotated tag.

**Comment by pvuorela** [comment]
Created JB#54891 for keeping this in sync. Can be used for later updates too.

**Pull request merged**
